// Assuntos comuns por disciplina, pra dar sugestão rápida no onboarding e em
// Planejamento — a maioria dos concursos cobra praticamente os mesmos temas
// em cada disciplina, só varia o recorte. Não é o índice de nenhum edital
// específico, é só um ponto de partida; a pessoa edita livremente.
// Chave = nome exato de uma disciplina em DISCIPLINAS_SUGERIDAS.
export const ASSUNTOS_SUGERIDOS: Record<string, string[]> = {
  "Direito Constitucional": [
    "Teoria da Constituição",
    "Poder Constituinte",
    "Controle de Constitucionalidade",
    "Direitos e Garantias Fundamentais",
    "Nacionalidade",
    "Direitos Políticos",
    "Organização do Estado",
    "Organização dos Poderes",
    "Administração Pública na Constituição",
    "Ordem Social",
  ],
  "Direito Administrativo": [
    "Princípios da Administração Pública",
    "Organização Administrativa",
    "Poderes Administrativos",
    "Atos Administrativos",
    "Licitações",
    "Contratos Administrativos",
    "Serviços Públicos",
    "Servidores Públicos",
    "Responsabilidade Civil do Estado",
    "Controle da Administração Pública",
    "Processo Administrativo",
    "Improbidade Administrativa",
  ],
  "Direito Penal": [
    "Princípios do Direito Penal",
    "Lei Penal no Tempo e no Espaço",
    "Teoria do Crime",
    "Tipicidade, Ilicitude e Culpabilidade",
    "Concurso de Pessoas",
    "Concurso de Crimes",
    "Penas",
    "Extinção da Punibilidade",
    "Crimes contra a Pessoa",
    "Crimes contra o Patrimônio",
    "Crimes contra a Administração Pública",
  ],
  "Direito Civil": [
    "Lei de Introdução às Normas do Direito Brasileiro",
    "Pessoas Naturais e Jurídicas",
    "Bens",
    "Fatos Jurídicos",
    "Prescrição e Decadência",
    "Obrigações",
    "Contratos",
    "Responsabilidade Civil",
    "Direito das Coisas",
    "Família",
    "Sucessões",
  ],
  "Direito Processual Civil": [
    "Princípios Processuais",
    "Jurisdição e Competência",
    "Partes e Procuradores",
    "Petição Inicial",
    "Resposta do Réu",
    "Provas",
    "Sentença e Coisa Julgada",
    "Recursos",
    "Cumprimento de Sentença",
    "Processo de Execução",
  ],
  "Direito Processual Penal": [
    "Princípios Processuais Penais",
    "Inquérito Policial",
    "Ação Penal",
    "Competência",
    "Prisões e Medidas Cautelares",
    "Provas",
    "Procedimentos",
    "Recursos",
    "Nulidades",
  ],
  "Direito do Trabalho": [
    "Princípios do Direito do Trabalho",
    "Relação de Emprego",
    "Contrato de Trabalho",
    "Jornada de Trabalho",
    "Remuneração e Salário",
    "Férias",
    "Rescisão Contratual",
    "FGTS",
    "Segurança e Saúde no Trabalho",
    "Direito Coletivo do Trabalho",
  ],
  "Direito Tributário": [
    "Sistema Tributário Nacional",
    "Competência Tributária",
    "Espécies Tributárias",
    "Obrigação Tributária",
    "Crédito Tributário",
    "Lançamento",
    "Suspensão, Extinção e Exclusão do Crédito Tributário",
    "Garantias e Privilégios do Crédito Tributário",
    "Administração Tributária",
  ],
  "Direito Previdenciário": [
    "Seguridade Social",
    "Regime Geral de Previdência Social",
    "Segurados e Dependentes",
    "Benefícios Previdenciários",
    "Custeio da Previdência Social",
    "Aposentadorias",
    "Auxílios e Pensões",
  ],
  "Direito Ambiental": [
    "Princípios do Direito Ambiental",
    "Política Nacional do Meio Ambiente",
    "Licenciamento Ambiental",
    "Responsabilidade Ambiental",
    "Sistema Nacional de Unidades de Conservação",
    "Recursos Hídricos",
  ],
  "Direito Empresarial": [
    "Teoria Geral do Direito Empresarial",
    "Empresário e Sociedade Empresária",
    "Estabelecimento Empresarial",
    "Títulos de Crédito",
    "Falência e Recuperação Judicial",
    "Direito Societário",
  ],
  Matemática: [
    "Conjuntos Numéricos",
    "Razão e Proporção",
    "Porcentagem",
    "Regra de Três",
    "Equações e Inequações",
    "Funções",
    "Progressões Aritméticas e Geométricas",
    "Geometria Plana",
  ],
  "Raciocínio Lógico": [
    "Estruturas Lógicas",
    "Lógica Proposicional",
    "Diagramas Lógicos",
    "Sequências e Padrões",
    "Análise Combinatória",
    "Probabilidade",
    "Problemas de Raciocínio",
  ],
  Estatística: [
    "Estatística Descritiva",
    "Medidas de Tendência Central",
    "Medidas de Dispersão",
    "Probabilidade",
    "Distribuições de Probabilidade",
    "Amostragem",
  ],
  "Matemática Financeira": [
    "Juros Simples",
    "Juros Compostos",
    "Descontos",
    "Taxas de Juros",
    "Séries de Pagamentos",
    "Sistemas de Amortização",
  ],
  Física: ["Mecânica", "Termologia", "Óptica", "Eletricidade"],
  "Língua Portuguesa": [
    "Interpretação de Texto",
    "Ortografia",
    "Acentuação Gráfica",
    "Classes de Palavras",
    "Sintaxe",
    "Concordância Verbal e Nominal",
    "Regência Verbal e Nominal",
    "Crase",
    "Pontuação",
    "Figuras de Linguagem",
  ],
  Redação: ["Estrutura Textual", "Coesão e Coerência", "Gêneros Textuais", "Norma Culta", "Argumentação"],
  Geografia: [
    "Geografia Física do Brasil",
    "Geografia Humana e Econômica do Brasil",
    "Geopolítica",
    "Meio Ambiente",
    "Urbanização",
  ],
  História: [
    "História do Brasil Colônia",
    "Brasil Império",
    "República Velha",
    "Era Vargas",
    "Ditadura Militar",
    "Redemocratização",
  ],
  Atualidades: ["Política Nacional", "Economia", "Meio Ambiente", "Tecnologia", "Relações Internacionais"],
  "Direitos Humanos": [
    "Teoria Geral dos Direitos Humanos",
    "Declaração Universal dos Direitos Humanos",
    "Sistema Global de Proteção",
    "Sistema Interamericano de Proteção",
    "Direitos Humanos na Constituição de 1988",
  ],
  Sociologia: ["Teorias Sociológicas Clássicas", "Cultura e Sociedade", "Estratificação Social", "Movimentos Sociais"],
  Filosofia: ["Filosofia Antiga", "Filosofia Moderna", "Ética", "Filosofia Política"],
  "Informática Básica": [
    "Sistema Operacional Windows",
    "Editor de Texto (Word)",
    "Planilha Eletrônica (Excel)",
    "Internet e Navegadores",
    "Correio Eletrônico",
  ],
  "Segurança da Informação": ["Conceitos de Segurança", "Criptografia", "Malware", "Backup", "Políticas de Segurança"],
  "Redes de Computadores": [
    "Conceitos Básicos de Redes",
    "Modelo OSI e TCP/IP",
    "Protocolos de Rede",
    "Equipamentos de Rede",
  ],
  "Banco de Dados": ["Modelo Relacional", "SQL", "Normalização", "Modelagem de Dados"],
  "Lógica de Programação": [
    "Algoritmos",
    "Estruturas de Controle",
    "Estruturas de Dados",
    "Programação Orientada a Objetos",
  ],
  "Governança de TI": ["COBIT", "ITIL", "Gestão de Projetos"],
  Inglês: ["Interpretação de Texto", "Gramática", "Vocabulário", "Falsos Cognatos"],
  Espanhol: ["Interpretação de Texto", "Gramática", "Vocabulário", "Falsos Cognatos"],
  Francês: ["Interpretação de Texto", "Gramática", "Vocabulário", "Falsos Cognatos"],
};
