// Lista curada dos concursos mais buscados, só pra dar sugestão rápida no
// onboarding. Não é uma base completa — quem não encontrar o seu digita
// livremente mesmo, o campo aceita texto livre.
export const CONCURSOS_SUGERIDOS = [
  "PRF — Polícia Rodoviária Federal",
  "PF — Polícia Federal",
  "Polícia Civil",
  "Polícia Militar",
  "Polícia Penal",
  "Corpo de Bombeiros Militar",
  "Guarda Municipal",
  "Receita Federal — Auditor Fiscal",
  "SEFAZ — Fiscal de Rendas Estadual",
  "INSS — Técnico do Seguro Social",
  "TCU — Tribunal de Contas da União",
  "TCE — Tribunal de Contas do Estado",
  "TRF — Tribunal Regional Federal",
  "TRT — Tribunal Regional do Trabalho",
  "TRE — Tribunal Regional Eleitoral",
  "Tribunal de Justiça — Escrevente/Analista",
  "STJ — Superior Tribunal de Justiça",
  "Magistratura Estadual",
  "Magistratura Federal",
  "Ministério Público Estadual",
  "Ministério Público da União",
  "Defensoria Pública Estadual",
  "Defensoria Pública da União",
  "Procuradoria da Fazenda Nacional",
  "Advocacia-Geral da União",
  "Câmara dos Deputados",
  "Senado Federal",
  "Banco Central do Brasil",
  "Banco do Brasil",
  "Caixa Econômica Federal",
  "Correios",
  "IBGE",
  "ANATEL",
  "ANVISA",
  "ANAC — Agência Nacional de Aviação Civil",
];
