// Lista curada dos concursos mais buscados, só pra dar sugestão rápida no
// onboarding. Não é uma base completa — quem não encontrar o seu digita
// livremente mesmo, o campo aceita texto livre.
export const CONCURSOS_SUGERIDOS = [
  "PRF — Polícia Rodoviária Federal",
  "PF — Delegado de Polícia Federal",
  "PF — Agente de Polícia Federal",
  "PF — Escrivão de Polícia Federal",
  "PF — Perito Criminal Federal",
  "PF — Papiloscopista Policial Federal",
  "Polícia Civil — Delegado",
  "Polícia Civil — Escrivão",
  "Polícia Civil — Investigador/Agente",
  "Polícia Civil — Perito Criminal",
  "PCDF — Polícia Civil do Distrito Federal",
  "Polícia Militar — Soldado",
  "Polícia Militar — Oficial",
  "PMDF — Polícia Militar do Distrito Federal",
  "Polícia Penal",
  "Polícia Penal Federal",
  "Corpo de Bombeiros Militar — Soldado",
  "Corpo de Bombeiros Militar — Oficial",
  "Guarda Municipal",
  "Guarda Civil Municipal (GCM)",
  "Polícia Legislativa — Câmara dos Deputados",
  "Polícia Legislativa — Senado Federal",
  "DEPEN — Agente Penitenciário Federal",
  "ABIN — Agente de Inteligência",
  "Perito Criminal",
  "Polícia Científica",
  "Receita Federal — Auditor Fiscal",
  "SEFAZ — Fiscal de Rendas Estadual",
  "INSS — Técnico do Seguro Social",
  "TCU — Tribunal de Contas da União",
  "TCE — Tribunal de Contas do Estado",
  "TRF — Tribunal Regional Federal",
  "TRT — Tribunal Regional do Trabalho",
  "TRE — Tribunal Regional Eleitoral",
  "Tribunal de Justiça — Escrevente/Analista",
  "STJ — Superior Tribunal de Justiça",
  "Magistratura Estadual",
  "Magistratura Federal",
  "Ministério Público Estadual",
  "Ministério Público da União",
  "Defensoria Pública Estadual",
  "Defensoria Pública da União",
  "Procuradoria da Fazenda Nacional",
  "Advocacia-Geral da União",
  "Câmara dos Deputados",
  "Senado Federal",
  "Banco Central do Brasil",
  "Banco do Brasil",
  "Caixa Econômica Federal",
  "Correios",
  "IBGE",
  "ANATEL",
  "ANVISA",
  "ANAC — Agência Nacional de Aviação Civil",
];
